### ISSUE TITLE
'engine.h' file not found

### ISSUE THREAD

**Issue by Bushite** [NYUGraphics/GM_Assignment_1#1]
Hi all,

When I tried compiling libigl's tutorials, an error occurred, saying 'engine.h' file not found. Here's the screen shot of the log. Has anyone else who encountered the same problem?
![image](https://user-images.githubusercontent.com/26162141/35768380-d3ee12de-08c8-11e8-8a7a-a00e3c9962ec.png)

Thanks,
Boran

**Comment by danielepanozzo** [comment]
It is finding a matlab installation path, but it fails at finding the headers for the matlab engine. Maybe you had MATLAB installed and then you unistalled it without cleaning the path?

Anyway, the error should go away if you disable the matlab support for libigl, by adding the option "-DLIBIGL_WITH_MATLAB=OFF" to the cmake command line (after deleting the cmake cache).

**Comment by Bushite** [comment]
Thanks! It went well with the option, but if I want to add Matlab support, where should I modify the path. I have Matlab installed on my computer.

**Comment by Bushite** [comment]
Thanks! It went well with the option, but if I want to add Matlab support, where should I modify the path? I have Matlab installed on my computer. @danielepanozzo

**Comment by danielepanozzo** [comment]
We will not need the matlab functions for this class. If you want to keep it enabled, you will have to figure out why your cmake installation is successfully finding matlab, but somehow not finding engine.h. If you pass by in the office hours next week we can take a look at it together.
