### ISSUE TITLE
Build failure using CLion

### ISSUE THREAD

**Issue by majia67** [NYUGraphics/GM_Assignment_1#2]
I recently decided to use CLion as the main developing environment, but I encountered the following error when trying to build this assignment.

See the log here: https://gist.github.com/majia67/a7a6997471a6d37a448d067277a83327

I can use Visual Studio 2017 to build the project with slight modifications.

My building environment:
OS: Windows 10 Build 1709
CLion: 2017.3.3
Toolchain: CMake 3.9.6 + MinGW

Any suggestions are welcome!

**Comment by danielepanozzo** [comment]
libigl does not compile with MinGW, we are only supporting the microsoft compiler (VS2015 or VS2017). It does compile with clang, if it is possible to use clang with clion on windows that should work, but I recommend to keep it simple and use the Visual Studio 2017 IDE if you are on windows.

**Comment by majia67** [comment]
Thank you very much for your prompt reply! I will keep using VS2017 then.
