### ISSUE TITLE
new libigl release breaks the homework Travis CI test

### ISSUE THREAD

**Issue by majia67** [NYUGraphics/GM_Assignment_1#3]
I just found that libigl changes its header file structure, and the "igl/viewer/Viewer.h" file does not exist. [See is the Travis CI build record for further information](https://gist.github.com/majia67/238b4b75bc5b588aa5da4aa04834689d). I guess any recent clone of the libigl repository would break the homework build. Any suggestions on how to solve this?

**Comment by danielepanozzo** [comment]
Hi,

yes the last update to libigl broke the assignment code. For now, please use this version of libigl:
https://github.com/libigl/libigl/tree/7fb0ce4ee61ae93f57d9d53c70f1bd90be7dd364

If you already updated, you can rollback with:
git reset --hard 7fb0ce4ee61ae93f57d9d53c70f1bd90be7dd364
git submodule update

Have a good we,
Daniele

**Comment by majia67** [comment]
Thanks! That unbreaks doing the assignment. However, Travis CI build would still fail. I guess we need to either reconfigure Travis CI to use this specific commit of libigl, or we need to adapt the assignment to the new libigl structure.

**Comment by jiangzhongshi** [comment]
Hi Yicong,

Yes, you are right. Please update `.travis.yml` as this https://github.com/NYUGeometricModeling/GM_Assignment_2/blob/master/.travis.yml

I will send out instructions for students soon.

Best,
Zhongshi

**Comment by majia67** [comment]
Thanks, Zhongshi! The updated .travis.yml file fixes the problem.
