### ISSUE TITLE
igl viewer toolbox does not display

### ISSUE THREAD

**Issue by majia67** [NYUGraphics/GM_Assignment_1#4]
I can't see igl viewer toolbox when viewing the mesh. Do I need to toggle it manually or enable it during the build?

Below is a screenshot of viewing mesh:
![image](https://user-images.githubusercontent.com/11867815/36356376-3512db4c-14bf-11e8-9d01-c2ddca7e4f24.png)

Testing environment:
OS: Windows 10
IDE: VS 2017
Build Mode: x64 Release

**Comment by danielepanozzo** [comment]
I cannot reproduce it on macosx. Can you check if the NANOGUI option enabled in your cmake file?
```cpp
option(LIBIGL_WITH_NANOGUI     "Use Nanogui menu"   ON)
```

If it is on and the bar is not visible, you can try to delete CMakeCache.txt and rerun cmake.
The bar is not strictly necessary for this assignment (you can use the keyboard callbacks for the various steps), if it does not work, we can try to figure it out together during the office hours.

**Comment by majia67** [comment]
Thanks! After enabling NANOGUI option, I can see the viewer toolbox now. A smaller issue is the toolbox does not scale correctly in my window:

![image](https://user-images.githubusercontent.com/11867815/36356657-f1a6f6be-14c2-11e8-8251-d8eeff8b1d4c.png)

However, it seems to scale correctly on Windows 7 as I saw this screenshot in the tutorial: http://libigl.github.io/libigl/tutorial/tutorial.html#visualizingsurfaces

**Comment by majia67** [comment]
By the way, the NANOGUI option is by default disabled in the CMakeLists.txt file in the assignment repository. Is this due to the consideration of the building time?

**Comment by jiangzhongshi** [comment]
I believe there was some problem for Travis last year. I can try to check it.

**Comment by danielepanozzo** [comment]
Yes, it is tricky (and unnecessary) to compile NANOGUI on travis. It is best to leave it disabled for the continuous integration.
