### ISSUE TITLE
Do you have any recommendations to set libigl path?

### ISSUE THREAD

**Issue by LihengGong** [NYUGraphics/GM_Assignment_1#7]
Any recommendation to set libigl path?

If I download the code directly, I'm having trouble to compile it.

When executing `mkdir build; cd build; cmake ../`, this error pops up:

>CMake Error at cmake/FindLIBIGL.cmake:39 (include):
  include could not find load file:

    libigl
>Call Stack (most recent call first):
  CMakeLists.txt:36 (find_package)

I have to manually set libigl's path to compile the project successfully:
(in FindLIBIGL.cmake, change the last but one line to: `list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/external/libigl/cmake")`)

But the approach above feels more like a hack.
Do you have any recommendations for a more elegant solution? Or do I miss any steps/configurations?

I also tried to set 
```bash
export LIBIGL="/Users/gongliheng/Documents/gp/hw1/libigl"
export LIBIGL_INCLUDE_DIR="/Users/gongliheng/Documents/gp/hw1/libigl"
```
in my bashrc but that does not help.

I'm using MacOS with the latest CMAKE.

Thank you!

**Comment by jiangzhongshi** [comment]
Can you remove the entire external folder, and do cmake again, what is the complete output?

**Comment by LihengGong** [comment]
Deleting external directory is not helping:

>[ 11%] Creating directories for 'libigl-download'
[ 22%] Performing download step (git clone) for 'libigl-download'
Cloning into 'libigl'...
Note: checking out 'e699d257fe860d4fd82709835e72438bd0cd1533'.

>You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

>If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

>HEAD is now at e699d257 Update hausdorff.h
[ 33%] No patch step for 'libigl-download'
[ 44%] Performing update step for 'libigl-download'
[ 55%] No configure step for 'libigl-download'
[ 66%] No build step for 'libigl-download'
[ 77%] No install step for 'libigl-download'
[ 88%] No test step for 'libigl-download'
[100%] Completed 'libigl-download'
[100%] Built target libigl-download
CMake Error at cmake/FindLIBIGL.cmake:37 (include):
  include could not find load file:

    libigl
>Call Stack (most recent call first):
  CMakeLists.txt:36 (find_package)

**Comment by LihengGong** [comment]
I can see the following line in `FindLIBIGL.cmake`, but it seems that it is not taking effect.
```
find_path(LIBIGL_INCLUDE_DIR igl/readOBJ.h
    PATHS
       ${CMAKE_SOURCE_DIR}/external/libigl
```

**Comment by LihengGong** [comment]
I found that uncomment this line in `FindLIBIGL.cmake` can make compilation work now.
```
            ENV LIBIGL
```

**Comment by jiangzhongshi** [comment]
Hi Liheng,

You are correct in identifying the problem. That part is indeed how cmake find libigl. Your method set libigl as environment variable `LIBIGL`, which wouldn't make a difference, but is not what I intended. 

Can you confirm that `external/libigl/cmake/` is non-empty? And do you reproduce the same effect if you re-do the git clone from the very beginning?

**Comment by LihengGong** [comment]
Sorry for the late response.

I tried to start afresh and the error is still there.

Environment:
MacOS 10.14.3 + cmake version 3.13.4 + Apple LLVM version 10.0.0 (clang-1000.11.45.5)

Steps:
- make a new dir, cd into that dir and git clone:
 ```
  git clone --recursive https://github.com/NYUGraphics/GM_Assignment_1.git
 ```

- in source root directory:
```
 mkdir build; cd build; cmake ../
```

And the error output is:
```
 mkdir build && cd build && cmake ..
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Downloading/updating libigl
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/gongliheng/Documents/gp/newhw1/GM_Assignment_1/external/.cache/libigl
Scanning dependencies of target libigl-download
[ 11%] Creating directories for 'libigl-download'
[ 22%] Performing download step (git clone) for 'libigl-download'
Cloning into 'libigl'...
Note: checking out 'e699d257fe860d4fd82709835e72438bd0cd1533'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e699d257 Update hausdorff.h
[ 33%] No patch step for 'libigl-download'
[ 44%] Performing update step for 'libigl-download'
[ 55%] No configure step for 'libigl-download'
[ 66%] No build step for 'libigl-download'
[ 77%] No install step for 'libigl-download'
[ 88%] No test step for 'libigl-download'
[100%] Completed 'libigl-download'
[100%] Built target libigl-download
CMake Error at cmake/FindLIBIGL.cmake:37 (include):
  include could not find load file:

    libigl
Call Stack (most recent call first):
  CMakeLists.txt:36 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/gongliheng/Documents/gp/newhw1/GM_Assignment_1/build/CMakeFiles/CMakeOutput.log".
```

I checked external/libigl/cmake and it is not empty:

```
 $> pwd
~/Documents/gp/newhw1/GM_Assignment_1/external/libigl/cmake
 $> l
total 224
drwxr-xr-x  11 gongliheng  staff   352B Feb 11 17:05 .
drwxr-xr-x  17 gongliheng  staff   544B Feb 11 17:05 ..
-rw-r--r--   1 gongliheng  staff   5.5K Feb 11 17:05 CXXFeatures.cmake
-rw-r--r--   1 gongliheng  staff   688B Feb 11 17:05 DownloadProject.CMakeLists.cmake.in
-rw-r--r--   1 gongliheng  staff   7.9K Feb 11 17:05 DownloadProject.cmake
-rw-r--r--   1 gongliheng  staff   1.1K Feb 11 17:05 FindCORK.cmake
-rw-r--r--   1 gongliheng  staff    49K Feb 11 17:05 FindMATLAB.cmake
-rw-r--r--   1 gongliheng  staff   1.0K Feb 11 17:05 FindMOSEK.cmake
-rw-r--r--   1 gongliheng  staff   4.6K Feb 11 17:05 LibiglDownloadExternal.cmake
-rw-r--r--   1 gongliheng  staff   736B Feb 11 17:05 libigl-config.cmake.in
-rw-r--r--   1 gongliheng  staff    17K Feb 11 17:05 libigl.cmake
```

**Comment by jiangzhongshi** [comment]
Hi,

This is really weird, can you come to the office hour of mine next week, or of @danielepanozzo 's tomorrow?

**Comment by LihengGong** [comment]
I managed to locate the root cause by comparing my configuration with that of my classmate:

I wrongly placed directory `igl` into my system folder `/usr/local` and it is the source of all the troubles.
After deleting that directory, all issues are resolved.
